version: '3.4'

services:
  tinyapp:
    image: tinyapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
    env_file:
    - secret.env
    ports:
      - 8080:8080
